package com.desperta;

import static org.junit.Assert.*;

import android.app.Activity;
import android.content.*;
import android.os.*;
import androidx.lifecycle.Lifecycle;
import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.uiautomator.*;
import org.junit.*;
import org.junit.runner.RunWith;

/** Requires emulator camera-back imagefile generated by scripts/camera-fixture.py. */
@RunWith(AndroidJUnit4.class)
public class CameraPipelineTest {
  Context c;
  UiDevice ui;

  @Before
  public void before() throws Exception {
    c = InstrumentationRegistry.getInstrumentation().getTargetContext();
    ui = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
    try (ParcelFileDescriptor p =
        InstrumentationRegistry.getInstrumentation()
            .getUiAutomation()
            .executeShellCommand("pm grant com.desperta android.permission.CAMERA")) {
      new java.io.FileInputStream(p.getFileDescriptor()).readAllBytes();
    }
    c.stopService(new Intent(c, AlarmService.class));
    SystemClock.sleep(200);
    Store.prefs(c).edit().clear().commit();
  }

  @After
  public void after() {
    c.stopService(new Intent(c, AlarmService.class));
    for (Alarm a : Store.all(c)) Scheduler.cancel(c, a.id);
    Store.prefs(c).edit().clear().commit();
  }

  void waitFinished(ActivityScenario<?> s) {
    long end = SystemClock.elapsedRealtime() + 25000;
    while (SystemClock.elapsedRealtime() < end) {
      try {
        if (s.getState() == Lifecycle.State.DESTROYED) return;
      } catch (NullPointerException transitioning) {
      }
      SystemClock.sleep(200);
    }
    fail("Camera did not complete QR scan");
  }

  @Test
  public void registerFromCameraAndMatchRegisteredCode() throws Exception {
    String registered;
    try (ActivityScenario<MissionActivity> s =
        ActivityScenario.launchActivityForResult(
            new Intent(c, MissionActivity.class)
                .putExtra("type", "barcode")
                .putExtra("mode", "register"))) {
      waitFinished(s);
      assertEquals(Activity.RESULT_OK, s.getResult().getResultCode());
      registered = s.getResult().getResultData().getStringExtra("target");
      assertEquals("DESPERTA-ACORDAR-2026", registered);
    }
    try (ActivityScenario<MissionActivity> s =
        ActivityScenario.launchActivityForResult(
            new Intent(c, MissionActivity.class)
                .putExtra("type", "barcode")
                .putExtra("target", registered))) {
      waitFinished(s);
      assertEquals(Activity.RESULT_OK, s.getResult().getResultCode());
    }
  }

  @Test
  public void wrongCameraCodeDoesNotCompleteMission() throws Exception {
    try (ActivityScenario<MissionActivity> s =
        ActivityScenario.launchActivityForResult(
            new Intent(c, MissionActivity.class)
                .putExtra("type", "barcode")
                .putExtra("target", "DIFFERENT-CODE"))) {
      assertTrue(ui.wait(Until.hasObject(By.textContains("não corresponde")), 25000));
      assertEquals(Lifecycle.State.RESUMED, s.getState());
      ui.pressBack();
      waitFinished(s);
      assertEquals(Activity.RESULT_CANCELED, s.getResult().getResultCode());
    }
  }

  @Test
  public void actualBarcodeMissionStopsRealAlarmOnlyAfterCameraScan() throws Exception {
    Alarm a = new Alarm();
    a.id = 65001;
    a.days = 0;
    a.snoozeLimit = 0;
    a.missions.add(new Alarm.Mission("barcode", "DESPERTA-ACORDAR-2026", 1));
    Store.save(c, a);
    try (ActivityScenario<MainActivity> launcher = ActivityScenario.launch(MainActivity.class)) {
      launcher.onActivity(x -> AlarmService.start(x, a.id, false));
      SystemClock.sleep(400);
      try (ActivityScenario<RingActivity> ring =
          ActivityScenario.launch(new Intent(c, RingActivity.class).putExtra("alarm_id", a.id))) {
        long end = SystemClock.elapsedRealtime() + 25000;
        while (Store.history(c).length() == 0 && SystemClock.elapsedRealtime() < end)
          SystemClock.sleep(200);
        assertTrue("Camera completion must reach alarm service", Store.history(c).length() > 0);
        assertFalse(Store.get(c, a.id).enabled);
      }
    }
  }
}
