package com.desperta;

import static org.junit.Assert.*;

import android.app.Activity;
import android.content.*;
import android.os.*;
import androidx.lifecycle.Lifecycle;
import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.uiautomator.*;
import org.junit.*;
import org.junit.runner.RunWith;

/** Requires emulator camera-back imagefile generated by scripts/camera-fixture.py. */
@RunWith(AndroidJUnit4.class)
public class CameraPipelineTest {
  Context c;
  UiDevice ui;

  private String fixtureValue() {
    return InstrumentationRegistry.getArguments().getString("barcodeFixtureValue", "DESPERTA-ACORDAR-2026");
  }

  @Before
  public void before() throws Exception {
    c = InstrumentationRegistry.getInstrumentation().getTargetContext();
    ui = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
    try (ParcelFileDescriptor p =
        InstrumentationRegistry.getInstrumentation()
            .getUiAutomation()
            .executeShellCommand("pm grant com.desperta android.permission.CAMERA")) {
      new java.io.FileInputStream(p.getFileDescriptor()).readAllBytes();
    }
    c.stopService(new Intent(c, AlarmService.class));
    SystemClock.sleep(200);
    Store.prefs(c).edit().clear().commit();
  }

  @After
  public void after() {
    c.stopService(new Intent(c, AlarmService.class));
    for (Alarm a : Store.all(c)) Scheduler.cancel(c, a.id);
    Store.prefs(c).edit().clear().commit();
  }

  void waitFinished(ActivityScenario<?> s) {
    long end = SystemClock.elapsedRealtime() + 25000;
    while (SystemClock.elapsedRealtime() < end) {
      try {
        if (s.getState() == Lifecycle.State.DESTROYED) return;
      } catch (NullPointerException transitioning) {
      }
      SystemClock.sleep(200);
    }
    fail("Camera did not complete QR scan");
  }

  @Test
  public void scheduledCameraMissionWakesScreenAndStopsAlarm() throws Exception {
    Alarm alarm = new Alarm();
    alarm.id = 65002;
    alarm.days = 0;
    alarm.missions.add(new Alarm.Mission("barcode", fixtureValue(), 1));
    Store.save(c, alarm);
    try (ActivityScenario<MainActivity> launcher = ActivityScenario.launch(MainActivity.class)) {
      Scheduler.scheduleAt(c, alarm.id, System.currentTimeMillis() + 2500, false, false);
      ui.sleep();
      assertFalse(ui.isScreenOn());
      long deadline = SystemClock.elapsedRealtime() + 30000;
      while ((Store.history(c).length() == 0 || Store.getSession(c) != null)
          && SystemClock.elapsedRealtime() < deadline) SystemClock.sleep(100);
      assertTrue("Alarm must wake display for the camera", ui.isScreenOn());
      assertEquals("Scan must stop the scheduled alarm", 1, Store.history(c).length());
      assertEquals(null, Store.getSession(c));
      assertFalse(Store.get(c, alarm.id).enabled);
    } finally { ui.wakeUp(); ui.pressHome(); }
  }

  @Test
  public void registerFromCameraAndMatchRegisteredCode() throws Exception {
    String registered;
    try (ActivityScenario<MissionActivity> s =
        ActivityScenario.launchActivityForResult(
            new Intent(c, MissionActivity.class)
                .putExtra("type", "barcode")
                .putExtra("mode", "register"))) {
      waitFinished(s);
      assertEquals(Activity.RESULT_OK, s.getResult().getResultCode());
      registered = s.getResult().getResultData().getStringExtra("target");
      assertEquals(fixtureValue(), registered);
    }
    try (ActivityScenario<MissionActivity> s =
        ActivityScenario.launchActivityForResult(
            new Intent(c, MissionActivity.class)
                .putExtra("type", "barcode")
                .putExtra("target", registered)
                // A reusable mission may accept any selected code. Keep a non-matching
                // entry first so this catches regressions where RingActivity forwards only
                // the legacy single target instead of the complete target list.
                .putStringArrayListExtra(
                    MissionActivity.EXTRA_TARGETS,
                    new java.util.ArrayList<>(
                        java.util.Arrays.asList("DIFFERENT-CODE", registered))))) {
      waitFinished(s);
      assertEquals(Activity.RESULT_OK, s.getResult().getResultCode());
    }
  }

  @Test
  public void wrongCameraCodeDoesNotCompleteMission() throws Exception {
    try (ActivityScenario<MissionActivity> s =
        ActivityScenario.launchActivityForResult(
            new Intent(c, MissionActivity.class)
                .putExtra("type", "barcode")
                .putExtra("target", "DIFFERENT-CODE"))) {
      assertTrue(ui.wait(Until.hasObject(By.textContains("não está selecionado")), 25000));
      // The custom scanner remains visible after a decoded but unselected code so the user can
      // point at another object without reopening the camera.
      assertNotEquals(Lifecycle.State.DESTROYED, s.getState());
      ui.pressBack();
      assertTrue(ui.wait(Until.hasObject(By.text("Escanear código")), 3000));
      assertEquals(Lifecycle.State.RESUMED, s.getState());
      ui.pressBack();
      waitFinished(s);
      assertEquals(Activity.RESULT_CANCELED, s.getResult().getResultCode());
    }
  }

  @Test
  public void actualBarcodeMissionStopsRealAlarmOnlyAfterCameraScan() throws Exception {
    Alarm a = new Alarm();
    a.id = 65001;
    a.days = 0;
    a.snoozeLimit = 0;
    Alarm.Mission barcode = new Alarm.Mission("barcode", "DIFFERENT-CODE", 1);
    barcode.targets.add("DIFFERENT-CODE");
    barcode.targets.add(fixtureValue());
    a.missions.add(barcode);
    Store.save(c, a);
    try (ActivityScenario<MainActivity> launcher = ActivityScenario.launch(MainActivity.class)) {
      launcher.onActivity(x -> AlarmService.start(x, a.id, false));
      long end = SystemClock.elapsedRealtime() + 25000;
      while ((Store.history(c).length() == 0 || Store.getSession(c) != null)
          && SystemClock.elapsedRealtime() < end) SystemClock.sleep(100);
      assertTrue("Camera completion must reach alarm service", Store.history(c).length() > 0);
      assertEquals(null, Store.getSession(c));
      assertFalse(Store.get(c, a.id).enabled);
      // The service opens RingActivity itself. Creating another one here creates a
      // second result chain that users do not start, and races ActivityScenario.close().
      ui.waitForIdle();
      boolean resumed = false;
      end = SystemClock.elapsedRealtime() + 5000;
      while (!resumed && SystemClock.elapsedRealtime() < end) {
        try { resumed = launcher.getState() == Lifecycle.State.RESUMED; }
        catch (NullPointerException transitioning) { }
        if (!resumed) SystemClock.sleep(100);
      }
      assertTrue("Main screen must return after completing the alarm", resumed);
    }
  }

  @Test
  public void guidedPreviewRunsMissionWithoutWritingHistoryOrDisablingAlarm() throws Exception {
    Alarm preview = new Alarm();
    preview.id = 65003;
    preview.label = "Prévia";
    preview.enabled = true;
    preview.missions.add(new Alarm.Mission("typing", "ACORDAR", 1));
    Store.save(c, preview);
    try (ActivityScenario<RingActivity> ring =
        ActivityScenario.launch(
            new Intent(c, RingActivity.class)
                .putExtra(Scheduler.EXTRA_ALARM_ID, preview.id)
                .putExtra(Scheduler.EXTRA_PREVIEW, true))) {
      assertTrue(ui.wait(Until.hasObject(By.text("Digitar resposta")), 5000));
      ui.findObject(new UiSelector().text("Digitar resposta")).click();
      assertTrue(ui.wait(Until.hasObject(By.text("Texto a digitar: ACORDAR")), 5000));
      ui.findObject(new UiSelector().className("android.widget.EditText")).setText("ACORDAR");
      ui.findObject(new UiSelector().text("Verificar texto")).click();
      assertTrue(ui.wait(Until.hasObject(By.text("Alarme desligado. Bom dia!")), 5000));
      assertEquals(0, Store.history(c).length());
      assertTrue(Store.get(c, preview.id).enabled);
    } finally {
      c.stopService(new Intent(c, AlarmService.class));
    }
  }
}
