plugins { id 'com.android.application' }
android {
 namespace 'com.desperta'
 compileSdk 36
 defaultConfig { applicationId 'com.desperta'; minSdk 26; targetSdk 35; versionCode 4; versionName '1.3.0'; testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
 buildTypes { release { minifyEnabled false } }
 testOptions { unitTests.returnDefaultValues = true }
}
dependencies {
 implementation 'androidx.activity:activity:1.10.1'
 implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
 implementation 'com.google.mlkit:image-labeling:17.0.9'
 implementation 'com.google.mlkit:pose-detection:18.0.0-beta5'
 testImplementation 'junit:junit:4.13.2'
 testImplementation 'org.json:json:20240303'
 androidTestImplementation 'androidx.test:runner:1.6.2'
 androidTestImplementation 'androidx.test:rules:1.6.1'
 androidTestImplementation 'androidx.test.ext:junit:1.2.1'
 androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
 androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
